/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import javax.swing.JDesktopPane;
import javax.swing.JLayeredPane;

/**
 *
 * @author deciodecarvalho
 */
public class TelaMenu extends javax.swing.JFrame {

    private static final int DT_WIDTH = 700;
    private static final int DT_HEIGHT = 500;

    private static final Dimension DESKTOP_SIZE = new Dimension(DT_WIDTH, DT_HEIGHT);
    private JDesktopPane desktop = new JDesktopPane();

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        
        //JDesktopPane desktop = new JDesktopPane();
        desktop.setPreferredSize(DESKTOP_SIZE);
        initComponents();
        
        this.pack();
        String pathProjeto = System.getProperty("user.dir")+"//";
        String iconPetfast = pathProjeto + "Imagens//Icone.png";
        //System.out.println(iconPetfast);
        setIconImage(Toolkit.getDefaultToolkit().getImage( iconPetfast ));
        //setIconImage(new ImageIcon(getClass().getResource(pathProjeto + "src//Icones//petfastIcone.ico")));
        setExtendedState(MAXIMIZED_BOTH); //maximizar a tela principal
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuArquivoJTable = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArquivo.setText("Arquivo");

        menuArquivoJTable.setText("TabelaAgendamento");
        menuArquivoJTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoJTableActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoJTable);

        jMenuBar1.add(menuArquivo);

        menuConsulta.setText("Consultar");
        jMenuBar1.add(menuConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuArquivoJTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoJTableActionPerformed
        // TODO add your handling code here:
        String titulo;
        titulo = "Tabela Agendamento";
        
        TelaAgendamentoTabela telaAgendamento = new TelaAgendamentoTabela();
        telaAgendamento.setTitle(titulo);
        telaAgendamento.pack();
        telaAgendamento.setLocation(50, 50); //(ponto inicial apartir lateral,altura)
        telaAgendamento.setVisible(true);
        
        add(telaAgendamento, JLayeredPane.DRAG_LAYER);

        telaAgendamento.setDefaultCloseOperation(1);//DISPOSE_ON_CLOSE
        
        
    }//GEN-LAST:event_menuArquivoJTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuArquivoJTable;
    private javax.swing.JMenu menuConsulta;
    // End of variables declaration//GEN-END:variables
}
